### ISSUE TITLE
svg

### ISSUE THREAD

**Issue by Dream-cxc** [limuyang2/CardSearchView#1]
哪些svg 你是在网上 找的 还是 手写的，有何快速入门吗

**Comment by limuyang2** [comment]
svg不是手写的，基本没人能手写的了。svg是由AI或者Photoshop制作png图标后转换过来的。也可以去阿里巴巴图标网站上去找图，那里可以下载svg

**Comment by Dream-cxc** [comment]
总要有一些 svg找不到吧

**Comment by limuyang2** [comment]
这是当然的，不可能全部找到。所以需要制作svg，先需要用AI或者PS做出图，然后再转换为SVG

**Comment by Dream-cxc** [comment]
这 svg 都是 美工 做的吗
